-- Create a storage bucket for training media (images generated by AI or uploaded by admins).
INSERT INTO storage.buckets (id, name, public)
VALUES ('training-media', 'training-media', true)
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users to upload media.
CREATE POLICY IF NOT EXISTS "Authenticated users can upload training media"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'training-media');

-- Allow public read access for training media.
CREATE POLICY IF NOT EXISTS "Public read access for training media"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'training-media');

-- Allow authenticated users to delete their uploads.
CREATE POLICY IF NOT EXISTS "Authenticated users can delete training media"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'training-media');
